# Dependencies
markdown:         kramdown
plugins:             [jekyll-paginate]

highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            SRLM
tagline:          'Programming and Hardware'
url:              http://srlm.io
paginate:         8
baseurl:          /
author:
  name:           Cody Lewis
  url:            https://github.com/srlm-io
  email:          srlm@srlm.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/srlm-io

excerpt_separator: <!--endexcerpt-->
